(() => {
  //console.clear();
  // let tbody = document.getElementsByClassName('redacted')[0].childNodes[1].childNodes[3];
  // document.getElementsByTagName('table')[0].childNodes[3].rows[0];
  let csv = 'Name,Given Name,Additional Name,Family Name,Occupation,Notes,Photo,E-mail 1 - Type,E-mail 1 - Value,Organization 1 - Name,Organization 1 - Title,Organization 1 - Department,Website 1 - Type,Website 1 - Value\n';
  let tables = document.getElementsByTagName('table');
  for (var i = 0; i < tables.length; i++) {
    // let table = tables[i];
    let table = tables[i].childNodes[3]; // tbody
    for (var j = 0; row = table.rows[j]; j++) {
      if (row.innerText.includes('№')) {console.log('Header row:\n', row); continue;}
      for (var k = 0; col = row.cells[k].childNodes; k++) {
        let names = [col[7].innerText].concat(col[7].innerText.split(' '));
        csv =+ names[0] + ',' + names[1] + ',' + names[2] + ',' + names[3] ',Occupation,Autogenerated.,Photo,* Work,,reducted,reducted,reducted,* Work,reducted';
        //csv += [names[0], names[1], names[2], names[3]].join(',');
        //return console.log(csv);
        return console.log(row);
      }
    }
  }
})();
